using UnityEngine;
using UnityEditor;
using System.IO;
using System.Collections.Generic;
using System.Linq;

/// <summary>
/// 高级批量预制体创建工具 - 可视化编辑器窗口
/// 作者：AI助手
/// 功能：批量从Sprite创建预制体，支持组件配置、模板预设、自动分类等
/// </summary>
public class AdvancedPrefabCreator : EditorWindow
{
    #region 数据结构
    
    [System.Serializable]
    public class PrefabSettings
    {
        public string prefabName = "NewPrefab";
        public string savePath = "Assets/Prefabs/AutoGenerated";
        
        // Sprite Renderer 设置
        public string sortingLayerName = "Default";
        public int sortingOrder = 0;
        public Material material;
        
        // 组件选项
        public bool addBoxCollider2D = false;
        public bool addCircleCollider2D = false;
        public bool addPolygonCollider2D = false;
        public bool addRigidbody2D = false;
        public bool addDynamicSorting = false;
        public bool addAnimator = false;
        
        // Collider 设置
        public bool isTrigger = false;
        
        // Rigidbody2D 设置
        public RigidbodyType2D bodyType = RigidbodyType2D.Static;
    }
    
    public enum PrefabTemplate
    {
        Custom,          // 自定义
        StaticProp,      // 静态装饰物（树、石头）
        InteractiveProp, // 可交互道具（宝箱、门）
        AnimatedProp,    // 动画道具（篝火、水面）
        Building,        // 建筑
        Vegetation,      // 植被
        Collision        // 碰撞物
    }
    
    #endregion
    
    #region 变量
    
    private List<Sprite> selectedSprites = new List<Sprite>();
    private PrefabSettings settings = new PrefabSettings();
    private PrefabTemplate currentTemplate = PrefabTemplate.Custom;
    private Vector2 scrollPos;
    
    private bool showComponentSettings = true;
    private bool showAdvancedSettings = false;
    
    // 排序层列表
    private string[] sortingLayerNames;
    private int selectedSortingLayerIndex = 0;
    
    #endregion
    
    #region Unity 生命周期
    
    [MenuItem("Tools/高级预制体创建工具")]
    static void OpenWindow()
    {
        var window = GetWindow<AdvancedPrefabCreator>("预制体创建工具");
        window.minSize = new Vector2(400, 600);
        window.Show();
    }
    
    void OnEnable()
    {
        // 获取所有排序层
        RefreshSortingLayers();
        
        // 加载选中的Sprite
        LoadSelectedSprites();
        
        // 加载上次保存的路径
        LoadSettings();
    }
    
    void OnDisable()
    {
        // 保存当前设置
        SaveSettings();
    }
    
    void OnSelectionChange()
    {
        LoadSelectedSprites();
        Repaint();
    }
    
    #endregion
    
    #region GUI 绘制
    
    void OnGUI()
    {
        scrollPos = EditorGUILayout.BeginScrollView(scrollPos);
        
        DrawHeader();
        DrawSpriteSelection();
        DrawTemplateSelection();
        DrawBasicSettings();
        DrawComponentSettings();
        DrawAdvancedSettings();
        DrawActionButtons();
        
        EditorGUILayout.EndScrollView();
    }
    
    void DrawHeader()
    {
        EditorGUILayout.Space(10);
        EditorGUILayout.LabelField("🎨 高级预制体批量创建工具", EditorStyles.boldLabel);
        EditorGUILayout.Space(5);
        EditorGUILayout.HelpBox(
            "使用方法：\n" +
            "1. 在Project窗口选择一个或多个Sprite\n" +
            "2. 选择预设模板或自定义配置\n" +
            "3. 点击\"创建预制体\"按钮",
            MessageType.Info
        );
        EditorGUILayout.Space(10);
    }
    
    void DrawSpriteSelection()
    {
        EditorGUILayout.LabelField("📦 选中的Sprite", EditorStyles.boldLabel);
        
        if (selectedSprites.Count == 0)
        {
            EditorGUILayout.HelpBox("请在Project窗口中选择至少一个Sprite", MessageType.Warning);
        }
        else
        {
            EditorGUILayout.LabelField($"已选择 {selectedSprites.Count} 个Sprite:");
            
            // 显示前5个
            int displayCount = Mathf.Min(5, selectedSprites.Count);
            for (int i = 0; i < displayCount; i++)
            {
                EditorGUILayout.LabelField($"  • {selectedSprites[i].name}");
            }
            
            if (selectedSprites.Count > 5)
            {
                EditorGUILayout.LabelField($"  ... 还有 {selectedSprites.Count - 5} 个");
            }
        }
        
        EditorGUILayout.Space(10);
    }
    
    void DrawTemplateSelection()
    {
        EditorGUILayout.LabelField("🎯 预设模板", EditorStyles.boldLabel);
        
        PrefabTemplate newTemplate = (PrefabTemplate)EditorGUILayout.EnumPopup("模板类型", currentTemplate);
        
        if (newTemplate != currentTemplate)
        {
            currentTemplate = newTemplate;
            ApplyTemplate(currentTemplate);
        }
        
        // 模板说明
        string templateDescription = GetTemplateDescription(currentTemplate);
        if (!string.IsNullOrEmpty(templateDescription))
        {
            EditorGUILayout.HelpBox(templateDescription, MessageType.Info);
        }
        
        EditorGUILayout.Space(10);
    }
    
    void DrawBasicSettings()
    {
        EditorGUILayout.LabelField("⚙️ 基础设置", EditorStyles.boldLabel);
        
        // 保存路径
        EditorGUILayout.BeginHorizontal();
        settings.savePath = EditorGUILayout.TextField("保存路径", settings.savePath);
        if (GUILayout.Button("浏览", GUILayout.Width(60)))
        {
            string path = EditorUtility.OpenFolderPanel("选择保存路径", "Assets", "");
            if (!string.IsNullOrEmpty(path))
            {
                settings.savePath = "Assets" + path.Replace(Application.dataPath, "");
            }
        }
        EditorGUILayout.EndHorizontal();
        
        // Sorting Layer
        EditorGUILayout.BeginHorizontal();
        EditorGUILayout.LabelField("Sorting Layer", GUILayout.Width(146));
        selectedSortingLayerIndex = EditorGUILayout.Popup(selectedSortingLayerIndex, sortingLayerNames);
        settings.sortingLayerName = sortingLayerNames[selectedSortingLayerIndex];
        EditorGUILayout.EndHorizontal();
        
        // Sorting Order
        settings.sortingOrder = EditorGUILayout.IntField("Order in Layer", settings.sortingOrder);
        
        // Material
        settings.material = (Material)EditorGUILayout.ObjectField("Material", settings.material, typeof(Material), false);
        
        EditorGUILayout.Space(10);
    }
    
    void DrawComponentSettings()
    {
        showComponentSettings = EditorGUILayout.Foldout(showComponentSettings, "🔧 组件配置", true, EditorStyles.foldoutHeader);
        
        if (showComponentSettings)
        {
            EditorGUI.indentLevel++;
            
            // 碰撞器
            EditorGUILayout.LabelField("碰撞器 Colliders:", EditorStyles.boldLabel);
            settings.addBoxCollider2D = EditorGUILayout.Toggle("  Box Collider 2D", settings.addBoxCollider2D);
            settings.addCircleCollider2D = EditorGUILayout.Toggle("  Circle Collider 2D", settings.addCircleCollider2D);
            settings.addPolygonCollider2D = EditorGUILayout.Toggle("  Polygon Collider 2D", settings.addPolygonCollider2D);
            
            if (settings.addBoxCollider2D || settings.addCircleCollider2D || settings.addPolygonCollider2D)
            {
                EditorGUI.indentLevel++;
                settings.isTrigger = EditorGUILayout.Toggle("Is Trigger", settings.isTrigger);
                EditorGUI.indentLevel--;
            }
            
            EditorGUILayout.Space(5);
            
            // 物理
            EditorGUILayout.LabelField("物理 Physics:", EditorStyles.boldLabel);
            settings.addRigidbody2D = EditorGUILayout.Toggle("  Rigidbody 2D", settings.addRigidbody2D);
            
            if (settings.addRigidbody2D)
            {
                EditorGUI.indentLevel++;
                settings.bodyType = (RigidbodyType2D)EditorGUILayout.EnumPopup("Body Type", settings.bodyType);
                EditorGUI.indentLevel--;
            }
            
            EditorGUILayout.Space(5);
            
            // 其他组件
            EditorGUILayout.LabelField("其他组件 Others:", EditorStyles.boldLabel);
            settings.addDynamicSorting = EditorGUILayout.Toggle("  动态排序脚本", settings.addDynamicSorting);
            settings.addAnimator = EditorGUILayout.Toggle("  Animator", settings.addAnimator);
            
            EditorGUI.indentLevel--;
        }
        
        EditorGUILayout.Space(10);
    }
    
    void DrawAdvancedSettings()
    {
        showAdvancedSettings = EditorGUILayout.Foldout(showAdvancedSettings, "🔬 高级设置", true, EditorStyles.foldoutHeader);
        
        if (showAdvancedSettings)
        {
            EditorGUI.indentLevel++;
            EditorGUILayout.HelpBox("高级功能开发中...", MessageType.Info);
            EditorGUI.indentLevel--;
        }
        
        EditorGUILayout.Space(10);
    }
    
    void DrawActionButtons()
    {
        EditorGUILayout.BeginHorizontal();
        
        GUI.enabled = selectedSprites.Count > 0;
        if (GUILayout.Button("🚀 创建预制体", GUILayout.Height(40)))
        {
            CreatePrefabs();
        }
        GUI.enabled = true;
        
        if (GUILayout.Button("🔄 刷新选择", GUILayout.Height(40), GUILayout.Width(100)))
        {
            LoadSelectedSprites();
        }
        
        EditorGUILayout.EndHorizontal();
    }
    
    #endregion
    
    #region 核心逻辑
    
    void LoadSelectedSprites()
    {
        selectedSprites.Clear();
        
        foreach (Object obj in Selection.objects)
        {
            if (obj is Sprite sprite)
            {
                selectedSprites.Add(sprite);
            }
            else if (obj is Texture2D)
            {
                // 如果选中的是Texture，尝试加载其所有子Sprite
                string path = AssetDatabase.GetAssetPath(obj);
                Object[] assets = AssetDatabase.LoadAllAssetsAtPath(path);
                
                foreach (Object asset in assets)
                {
                    if (asset is Sprite subSprite)
                    {
                        selectedSprites.Add(subSprite);
                    }
                }
            }
        }
    }
    
    void RefreshSortingLayers()
    {
        sortingLayerNames = SortingLayer.layers.Select(l => l.name).ToArray();
        
        // 尝试找到"Default"或第一个
        selectedSortingLayerIndex = System.Array.IndexOf(sortingLayerNames, settings.sortingLayerName);
        if (selectedSortingLayerIndex < 0) selectedSortingLayerIndex = 0;
    }
    
    void ApplyTemplate(PrefabTemplate template)
    {
        switch (template)
        {
            case PrefabTemplate.StaticProp:
                // 静态装饰物：树、石头等
                settings.sortingLayerName = "Props";
                settings.sortingOrder = 2;
                settings.addPolygonCollider2D = true;
                settings.addBoxCollider2D = false;
                settings.addCircleCollider2D = false;
                settings.isTrigger = false;
                settings.addRigidbody2D = false;
                settings.addDynamicSorting = true;
                settings.addAnimator = false;
                settings.savePath = "Assets/Prefabs/Environment/StaticProps";
                break;
                
            case PrefabTemplate.InteractiveProp:
                // 可交互道具：门、宝箱等
                settings.sortingLayerName = "Props";
                settings.sortingOrder = 5;
                settings.addBoxCollider2D = true;
                settings.addPolygonCollider2D = false;
                settings.addCircleCollider2D = false;
                settings.isTrigger = true;
                settings.addRigidbody2D = false;
                settings.addDynamicSorting = true;
                settings.addAnimator = true;
                settings.savePath = "Assets/Prefabs/Interactive";
                break;
                
            case PrefabTemplate.AnimatedProp:
                // 动画道具：篝火、水面等
                settings.sortingLayerName = "Props";
                settings.sortingOrder = 3;
                settings.addBoxCollider2D = false;
                settings.addPolygonCollider2D = false;
                settings.addCircleCollider2D = false;
                settings.isTrigger = false;
                settings.addRigidbody2D = false;
                settings.addDynamicSorting = false;
                settings.addAnimator = true;
                settings.savePath = "Assets/Prefabs/Environment/AnimatedProps";
                break;
                
            case PrefabTemplate.Building:
                // 建筑
                settings.sortingLayerName = "Props";
                settings.sortingOrder = 1;
                settings.addPolygonCollider2D = true;
                settings.addBoxCollider2D = false;
                settings.addCircleCollider2D = false;
                settings.isTrigger = false;
                settings.addRigidbody2D = false;
                settings.addDynamicSorting = true;
                settings.addAnimator = false;
                settings.savePath = "Assets/Prefabs/Environment/Buildings";
                break;
                
            case PrefabTemplate.Vegetation:
                // 植被：草、花等
                settings.sortingLayerName = "Ground";
                settings.sortingOrder = 5;
                settings.addBoxCollider2D = false;
                settings.addPolygonCollider2D = false;
                settings.addCircleCollider2D = false;
                settings.isTrigger = false;
                settings.addRigidbody2D = false;
                settings.addDynamicSorting = false;
                settings.addAnimator = false;
                settings.savePath = "Assets/Prefabs/Environment/Vegetation";
                break;
                
            case PrefabTemplate.Collision:
                // 碰撞物（不可见）
                settings.sortingLayerName = "Default";
                settings.sortingOrder = 0;
                settings.addBoxCollider2D = true;
                settings.addPolygonCollider2D = false;
                settings.addCircleCollider2D = false;
                settings.isTrigger = false;
                settings.addRigidbody2D = true;
                settings.bodyType = RigidbodyType2D.Static;
                settings.addDynamicSorting = false;
                settings.addAnimator = false;
                settings.savePath = "Assets/Prefabs/Collision";
                break;
        }
        
        // 刷新排序层索引
        RefreshSortingLayers();
    }
    
    string GetTemplateDescription(PrefabTemplate template)
    {
        switch (template)
        {
            case PrefabTemplate.StaticProp:
                return "静态装饰物：树木、石头、栅栏等。包含碰撞器和动态排序。";
            case PrefabTemplate.InteractiveProp:
                return "可交互道具：门、宝箱、开关等。包含触发器和动画器。";
            case PrefabTemplate.AnimatedProp:
                return "动画道具：篝火、水面、旗帜等。只包含动画器。";
            case PrefabTemplate.Building:
                return "建筑结构：房屋、桥梁等大型结构。包含碰撞器。";
            case PrefabTemplate.Vegetation:
                return "小型植被：草丛、花朵等地面装饰。无碰撞器。";
            case PrefabTemplate.Collision:
                return "隐形碰撞体：用于阻挡玩家的透明墙。";
            default:
                return "";
        }
    }
    
    void CreatePrefabs()
    {
        if (selectedSprites.Count == 0)
        {
            EditorUtility.DisplayDialog("错误", "请先选择至少一个Sprite！", "确定");
            return;
        }
        
        // 确保保存路径存在
        if (!Directory.Exists(settings.savePath))
        {
            Directory.CreateDirectory(settings.savePath);
            AssetDatabase.Refresh();
        }
        
        int successCount = 0;
        float progress = 0;
        
        foreach (Sprite sprite in selectedSprites)
        {
            progress++;
            EditorUtility.DisplayProgressBar("创建预制体", $"正在处理: {sprite.name}", progress / selectedSprites.Count);
            
            if (CreateSinglePrefab(sprite))
            {
                successCount++;
            }
        }
        
        EditorUtility.ClearProgressBar();
        AssetDatabase.Refresh();
        
        EditorUtility.DisplayDialog(
            "完成",
            $"成功创建了 {successCount}/{selectedSprites.Count} 个预制体！\n保存路径：{settings.savePath}",
            "确定"
        );
        
        Debug.Log($"✅ 批量创建预制体完成！成功：{successCount}，失败：{selectedSprites.Count - successCount}");
    }
    
    bool CreateSinglePrefab(Sprite sprite)
    {
        try
        {
            // 创建GameObject
            GameObject go = new GameObject(sprite.name);
            
            // 添加SpriteRenderer
            SpriteRenderer sr = go.AddComponent<SpriteRenderer>();
            sr.sprite = sprite;
            sr.sortingLayerName = settings.sortingLayerName;
            sr.sortingOrder = settings.sortingOrder;
            
            if (settings.material != null)
            {
                sr.material = settings.material;
            }
            
            // 添加碰撞器
            if (settings.addBoxCollider2D)
            {
                BoxCollider2D collider = go.AddComponent<BoxCollider2D>();
                collider.isTrigger = settings.isTrigger;
            }
            
            if (settings.addCircleCollider2D)
            {
                CircleCollider2D collider = go.AddComponent<CircleCollider2D>();
                collider.isTrigger = settings.isTrigger;
            }
            
            if (settings.addPolygonCollider2D)
            {
                PolygonCollider2D collider = go.AddComponent<PolygonCollider2D>();
                collider.isTrigger = settings.isTrigger;
            }
            
            // 添加Rigidbody2D
            if (settings.addRigidbody2D)
            {
                Rigidbody2D rb = go.AddComponent<Rigidbody2D>();
                rb.bodyType = settings.bodyType;
            }
            
            // 添加Animator
            if (settings.addAnimator)
            {
                go.AddComponent<Animator>();
            }
            
            // 添加动态排序脚本
            if (settings.addDynamicSorting)
            {
                go.AddComponent<DynamicSortingOrder>();
            }
            
            // 保存为预制体
            string prefabPath = $"{settings.savePath}/{sprite.name}.prefab";
            PrefabUtility.SaveAsPrefabAsset(go, prefabPath);
            
            // 删除临时GameObject
            DestroyImmediate(go);
            
            return true;
        }
        catch (System.Exception e)
        {
            Debug.LogError($"创建预制体失败: {sprite.name}\n错误: {e.Message}");
            return false;
        }
    }
    
    #endregion
    
    #region 设置保存与加载
    
    const string PREF_SAVE_PATH = "AdvancedPrefabCreator_SavePath";
    const string PREF_SORTING_LAYER = "AdvancedPrefabCreator_SortingLayer";
    const string PREF_SORTING_ORDER = "AdvancedPrefabCreator_SortingOrder";
    const string PREF_TEMPLATE = "AdvancedPrefabCreator_Template";
    
    void SaveSettings()
    {
        EditorPrefs.SetString(PREF_SAVE_PATH, settings.savePath);
        EditorPrefs.SetString(PREF_SORTING_LAYER, settings.sortingLayerName);
        EditorPrefs.SetInt(PREF_SORTING_ORDER, settings.sortingOrder);
        EditorPrefs.SetInt(PREF_TEMPLATE, (int)currentTemplate);
    }
    
    void LoadSettings()
    {
        if (EditorPrefs.HasKey(PREF_SAVE_PATH))
        {
            settings.savePath = EditorPrefs.GetString(PREF_SAVE_PATH, "Assets/Prefabs/AutoGenerated");
        }
        
        if (EditorPrefs.HasKey(PREF_SORTING_LAYER))
        {
            settings.sortingLayerName = EditorPrefs.GetString(PREF_SORTING_LAYER, "Default");
        }
        
        if (EditorPrefs.HasKey(PREF_SORTING_ORDER))
        {
            settings.sortingOrder = EditorPrefs.GetInt(PREF_SORTING_ORDER, 0);
        }
        
        if (EditorPrefs.HasKey(PREF_TEMPLATE))
        {
            currentTemplate = (PrefabTemplate)EditorPrefs.GetInt(PREF_TEMPLATE, 0);
        }
    }
    
    #endregion
}

